# Generated by Django 3.2.8 on 2024-06-13 04:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='watch_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='movie',
            name='watch_date',
            field=models.DateField(blank=True, null=True, verbose_name='視聴日時'),
        ),
    ]
